services:
  backend:
    container_name: lib-go-serv
    # image: lib-go:local
    # image: golang:1.21-alpine
    build: 
      context: ..
      dockerfile: build/package/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
        - ../.env

  db:
    restart: always
    container_name: lib-psql
    image: postgres:16
    env_file:
        - ../.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../third_party/postgres/.database/postgres/data:/var/lib/postgresql/data
      - ../init/sql:/docker-entrypoint-initdb.d

# volumes:
#   data:
