services:
  # backend:
  #   build: ../build/package 
  #   command: ../build/package/liblrelib
  #   depends_on:
  #     - psql
  #   ports:
  #     - 8080:8080

  psql:
    restart: always
    container_name: lib-psql
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
