services:
  backend:
    container_name: lib-go-serv
    image: lib-go
    # image: golang:1.21-alpine
    build: 
      context: ..
      dockerfile: build/package/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
        - ../.env

  db:
    restart: always
    container_name: lib-psql-serv
    image: postgres:16
    env_file:
        - ../.env
    ports:
      - 5438:5432
    environment:
      - POSTGRES_PASSWORD=12345
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../third_party/postgres/.database/postgres/data:/var/lib/postgresql/data
      - ../init/sql:/docker-entrypoint-initdb.d
