services:
  # backend:
  #   container_name: lib-go-serv
  #   image: golang:1.21-alpine
  #   build: 
  #     context: ../build/package/
  #   command: ../build/package/liblrelib
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
  #   env_file:
  #       - ../.env
  #   environment:
  #     - DATABASE_URL=postgres://${DB_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}?sslmode=disable

  db:
    restart: always
    container_name: lib-psql
    image: postgres:16
    ports:
      - 5438:5432
    environment:
      - POSTGRES_PASSWORD=12345
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../third_party/postgres/.database/postgres/data:/var/lib/postgresql/data
      # - ../init/sql:/docker-entrypoint-initdb.d
    # command: >
    #   sh -c "envsubst < /docker-entrypoint-initdb.d/init.sql | psql -U ${DB_USER} -d ${DB_NAME}"

volumes:
  data:
