env:  "dev"

level: "debug"

server:
  app_version: 1.0
  ssl_mode: disable
  read_timeout: 5s
  write_timeout: 5s
  # port: ${APP_PORT}

postgres:
  ssl_mode: disable
  # url: ${POSTGRES_URL}
  # host: ${POSTGRES_HOST}
  # port: ${POSTGRES_PORT}
  # username: ${DB_USER}
  # name: ${POSTGRES_DB}
  # password: ${POSTGRES_PASSWORD}
